general_knowledge_conversations = [
    "What is the capital of France?",
    "The capital of France is Paris.",
    "Who wrote 'To Kill a Mockingbird'?",
    "Harper Lee wrote 'To Kill a Mockingbird'.",
    "What is the speed of light?",
    "The speed of light is approximately 299,792 kilometers per second.",
    "Who was Albert Einstein?",
    "Albert Einstein was a theoretical physicist who developed the theory of relativity.",
    "What is the largest planet in our solar system?",
    "The largest planet in our solar system is Jupiter.",
    "Who painted the Mona Lisa?",
    "The Mona Lisa was painted by Leonardo da Vinci.",
    "What is the tallest mountain in the world?",
    "The tallest mountain in the world is Mount Everest.",
    "Who is the author of '1984'?",
    "George Orwell is the author of '1984'.",
    "What is the smallest country in the world?",
    "The smallest country in the world is Vatican City.",
    "What is the largest ocean on Earth?",
    "The largest ocean on Earth is the Pacific Ocean.",
    "Who discovered penicillin?",
    "Penicillin was discovered by Alexander Fleming.",
    "What is the hardest natural substance on Earth?",
    "The hardest natural substance on Earth is diamond.",
    "Who is known as the father of computers?",
    "Charles Babbage is known as the father of computers.",
    "What is the main ingredient in traditional Japanese miso soup?",
    "The main ingredient in traditional Japanese miso soup is miso paste.",
    "What is the chemical symbol for gold?",
    "The chemical symbol for gold is Au.",
    "What is the capital city of Japan?",
    "The capital city of Japan is Tokyo.",
    "What is the largest desert in the world?",
    "The largest desert in the world is the Sahara Desert.",
    "Who invented the telephone?",
    "The telephone was invented by Alexander Graham Bell.",
    "What is the boiling point of water?",
    "The boiling point of water is 100 degrees Celsius at standard atmospheric pressure.",
    "Who wrote 'Pride and Prejudice'?",
    "Jane Austen wrote 'Pride and Prejudice'.",
    "What is the longest river in the world?",
    "The longest river in the world is the Nile River.",
    "Who was the first president of the United States?",
    "The first president of the United States was George Washington.",
    "What is the chemical formula for water?",
    "The chemical formula for water is H2O.",
    "What is the most spoken language in the world?",
    "The most spoken language in the world is Mandarin Chinese.",
    "Who was William Shakespeare?",
    "William Shakespeare was an English playwright, poet, and actor.",
    "What is the largest continent?",
    "The largest continent is Asia.",
    "Who discovered America?",
    "Christopher Columbus is credited with discovering America in 1492.",
    "What is the primary component of the Earth's atmosphere?",
    "The primary component of the Earth's atmosphere is nitrogen, which makes up about 78%.",
    "What is the smallest bone in the human body?",
    "The smallest bone in the human body is the stapes bone, located in the middle ear.",
    "What is the most abundant element in the universe?",
    "The most abundant element in the universe is hydrogen.",
    "Who was the first person to walk on the moon?",
    "The first person to walk on the moon was Neil Armstrong.",
    "What is the largest mammal in the world?",
    "The largest mammal in the world is the blue whale.",
    "Who wrote the 'Iliad' and the 'Odyssey'?",
    "The 'Iliad' and the 'Odyssey' were written by Homer.",
    "What is the atomic number of carbon?",
    "The atomic number of carbon is 6.",
    "What is the tallest building in the world?",
    "As of 2021, the tallest building in the world is the Burj Khalifa in Dubai.",
    "Who developed the theory of evolution?",
    "The theory of evolution was developed by Charles Darwin.",
    "What is the main ingredient in guacamole?",
    "The main ingredient in guacamole is avocado.",
    "Who was the second president of the United States?",
    "The second president of the United States was John Adams.",
    "What is the capital of Australia?",
    "The capital of Australia is Canberra.",
    "What is the smallest planet in our solar system?",
    "The smallest planet in our solar system is Mercury.",
    "Who wrote 'The Great Gatsby'?",
    "F. Scott Fitzgerald wrote 'The Great Gatsby'.",
    "What is the largest organ in the human body?",
    "The largest organ in the human body is the skin."
]

